### ISSUE TITLE
Publish as npm module

### ISSUE THREAD

**Issue by phvannor** [Azure/azure-query-js#13]
Look at making queryjs an npm module so it can be a dependency for the JS SDK build process

**Comment by joewood** [comment]
Any update on this?

**Comment by phvannor** [comment]
Refactoring will wait a bit, the new Node.js Server (https://github.com/Azure/azure-mobile-apps-node/blob/master/package.json#L23) and the next JS SDK (https://github.com/Azure/azure-mobile-services/blob/offline/sdk/Javascript/package.json#L16) now take this via package.json to here.

@danderson00 and @shrishrirang can probably outline the current plans now for JS consumption.
