### ISSUE TITLE
Add includeDeleted function to query objects

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-query-js#18]
This would essentially be equivalent to

```
var query = new queryjs.Query('tableName')
query.includeDeleted = true
```

This greatly simplifies including deleted items from tables in azure-mobile-apps:

```
return context.tables('tableName').includeDeleted().read()
```

**Comment by adrianhall** [comment]
Is this released now?  If so, can we close it?

**Comment by danderson00** [comment]
Yeh, I must have added the resolves comment on the PR after it was merged.
