### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by RainerAtSpirit** [Azure/azure-query-js#7]
Both package.json https://github.com/WindowsAzure/queryjs/blob/dev/package.json#L10 and license.txt https://github.com/WindowsAzure/queryjs/blob/dev/LICENSE.txt state that this repo is under  Apache License  Version 2.0.

All *.coffee files under src https://github.com/WindowsAzure/queryjs/blob/dev/src/JavaScript.coffee#L1 however  have a closed license.

> Copyright (c) Microsoft Corporation. All rights reserved.

It would be good to know if this repo is covered by the `Apache License Version 2.0` or not.

**Comment by danderson00** [comment]
Hi @RainerAtSpirit, reviewing these issues, sorry it took us 3 years to respond :-P

The package is covered by the Apache 2.0 license. The copyright notices do not affect this.
